### ISSUE TITLE
Example of work

### ISSUE THREAD

**Issue by svinin** [agostinv/senior-capstone-obstacle-avoidance#3]
Hello. Is there any examples of work of this project? Maybe an article or a video?

**Comment by agostinv** [comment]
The final state of this repository doesn't quite reflect the final state of the project by the time I'd left, but there were issues with integration that made a practical showing impossible at the time. The lab that we handed this code off to has continued to use it as the base for the rest of their platform, as far as I know.

**Comment by svinin** [comment]
thanks
